pipeline {
    agent any

    environment {
        PROJECT_DIR = "Containers/rest-api-setup/docker/micro-auth/auth_api"
        TEST_FILE = "test_login.py"
    }

    stages {
        stage('Limpar Workspace') {
            steps {
                echo "Limpando arquivos antigos no workspace..."
                deleteDir()
            }
        }

        stage('Clonar Repositório') {
            steps {
                echo "Clonando o repositório..."
                checkout scm
            }
        }

        stage('Preparar Ambiente') {
            steps {
                dir("${PROJECT_DIR}") {
                    sh '''
                        echo "Criando ambiente virtual..."
                        python3 -m venv venv
                        . venv/bin/activate
                        echo "Atualizando pip e instalando dependências..."
                        pip install --upgrade pip
                        if [ -f requirements.txt ]; then
                            pip install -r requirements.txt
                        fi
                        echo "Instalando pytest..."
                        pip install pytest
                        echo "Ambiente virtual pronto!"
                    '''
                }
            }
        }

        stage('Executar Testes Unitários') {
            steps {
                dir("${PROJECT_DIR}") {
                    sh '''
                        echo "Executando pytest..."
                        . venv/bin/activate
                        pytest -v -s --tb=short test_login.py

                    '''
                }
            }
        }
    }

    post {
        always {
            echo 'Limpando o workspace ao final da execução...'
            deleteDir()
        }
    }
}
