pipeline {
    agent any

    environment {
        VENV_PATH = "venv"
        PROJECT_DIR = "dev_sec_ops_library_project/Containers/rest-api-setup/docker/micro-auth/auth_api"
        TEST_DIR = "tests-auth-logic"
    }

    stages {
        stage('Preparar Ambiente') {
            steps {
                dir("${PROJECT_DIR}") {
                    sh '''
                        echo "Criando ambiente virtual..."
                        python3 -m venv ${VENV_PATH}
                        . ${VENV_PATH}/bin/activate
                        echo "Instalando dependências..."
                        pip install --upgrade pip
                        if [ -f requirements.txt ]; then
                            pip install -r requirements.txt
                        fi
                    '''
                }
            }
        }

        stage('Executar Testes Unitários') {
            steps {
                dir("${PROJECT_DIR}") {
                    sh '''
                        echo "Executando pytest..."
                        . ${VENV_PATH}/bin/activate
                        ${VENV_PATH}/bin/pytest -v --tb=short ${TEST_DIR}
                    '''
                }
            }
        }
    }

    post {
        always {
            dir("${PROJECT_DIR}") {
                echo "Limpando ambiente virtual..."
                sh "rm -rf ${VENV_PATH}"
            }
        }
    }
}
